services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
        - plethora
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
        - plethora
  database:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: plethora
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
        - plethora

volumes:
  db_data:

networks:
  plethora: