services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - plethora

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - plethora

  database:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: plethora
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - plethora
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - plethora
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  db_data:

networks:
  plethora:
    driver: bridge
