services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
        - plethora
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
        - plethora
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - plethora
  database:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: plethora
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
        - plethora
    ports:
      - "5432:5432"

volumes:
  db_data:

networks:
  plethora:
    driver: bridge